CREATE TABLE IF NOT EXISTS bronze_ipc (
    fecha DATE NOT NULL,
    ipc DECIMAL NOT NULL
);

CREATE TABLE IF NOT EXISTS silver_ipc (
    fecha DATE NOT NULL,
    ipc DECIMAL NOT NULL
);

CREATE TABLE IF NOT EXISTS gold_ipc (
    id SERIAL PRIMARY KEY,
    fecha DATE UNIQUE NOT NULL,
	fecha_carga TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ipc DECIMAL NOT NULL
);