CREATE TABLE IF NOT EXISTS bronze_pbi (
    fecha DATE NOT NULL,
    pbi DECIMAL NOT NULL
);

CREATE TABLE IF NOT EXISTS silver_pbi (
    id SERIAL PRIMARY KEY,
    fecha DATE NOT NULL,
	fecha_carga TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pbi DECIMAL NOT NULL
);