CREATE TABLE IF NOT EXISTS bronze_ipc (
    fecha DATE NOT NULL,
    ipc DECIMAL NOT NULL
);

CREATE TABLE IF NOT EXISTS silver_ipc (
    id SERIAL PRIMARY KEY,
    fecha DATE NOT NULL,
	fecha_carga TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ipc DECIMAL NOT NULL
);