CREATE TABLE IF NOT EXISTS bronze_uf (
    fecha DATE NOT NULL,
    uf DECIMAL NOT NULL
);

CREATE TABLE IF NOT EXISTS silver_uf (
    fecha DATE NOT NULL,
    uf DECIMAL NOT NULL
);

CREATE TABLE IF NOT EXISTS gold_uf (
    id SERIAL PRIMARY KEY,
    fecha DATE UNIQUE NOT NULL,
	fecha_carga TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    uf DECIMAL NOT NULL
);